"""revision file

Revision ID: 1e95a4e06f3e
Revises: 03cca9d1c289
Create Date: 2023-10-17 23:14:06.004117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e95a4e06f3e'
down_revision: Union[str, None] = '03cca9d1c289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('files', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_constraint('files_user_id_fkey', 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key('files_user_id_fkey', 'files', 'users', ['user_id'], ['id'])
    op.alter_column('files', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('files', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
